update

diff --git a/resource/ui/tools/bin/extract b/resource/ui/tools/bin/extract
--- a/resource/ui/tools/bin/extract
+++ b/resource/ui/tools/bin/extract
@@ -1,11 +1,77 @@
 #!/bin/bash
-if [ -f $1 ] ; then
-    case $1 in
-        *.tar.bz2)    tar xvjf $1 ;;
-        *.tar.gz)     tar xvzf $1 ;;
-        *.zip)        unzip $1 ;;
-        *)            echo "don't know how to extract '$1'" ;;
-    esac
-else
-    echo "'$1' is not a valid file"
+PATH='/bin:/sbin:/usr/bin:/usr/sbin'
+
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+RED='\033[0;31m'
+BLUE='\033[0;34m'
+GRAY='\033[0;37m'
+NC='\033[0m'
+
+USAGE="${GRAY}===================usage${NC}
+${YELLOW}$(basename $0) ${BLUE}<archive(s)>${NC}
+
+Extracts the given archive(s) to the current directory."
+#
+#
+#==================================RUN
+if [ "$#" -lt 1 ]; then
+    echo -e "$USAGE"
+    exit 1
 fi
+
+is_installed() {
+    local app="$1"
+    local answ=$(dpkg-query -W -f='${Status}' "$app" 2>'/dev/null')
+    if ! echo "$answ" | grep 'install ok installed' &>'/dev/null'; then
+        echo -e "$app needed, install ?"
+        select _ in 'Yes' 'No'; do
+            case "$_" in
+                'Yes')
+                    echo -e "${BLUE}Installing$NC $app..."
+                    if ! apt install -y "$app" &>'/dev/null'; then
+                        echo -e "[$RED KO $NC] Non-zero returned from apt."
+                        echo -e 'sudo might be needed.'
+                        return 1
+                    else
+                        echo -e "[$GREEN OK $NC]"
+                        return 0
+                    fi
+                    ;;
+                'No') return 1;;
+            esac
+        done
+    else
+        return 0
+    fi
+}
+
+do_extract() {
+    local app="$1"
+    local cmd="$2"
+    if ! is_installed "$app"; then
+        echo -e "[$YELLOW WARN $NC] Can not extract $file"
+        return
+    fi
+    echo -ne "${BLUE}Extracting$NC $file..."
+    eval "$cmd"
+    echo -e "[$GREEN OK $NC]"
+}
+
+while [ "$#" -gt 0 ]; do
+    file="$1"
+    shift
+    if [ ! -e "$file" ]; then
+        echo -e "[$YELLOW WARN $NC] $file not found"
+        continue
+    fi
+    case "$file" in
+        *'.zip') do_extract 'unzip' "unzip -q '$file'";;
+        *'.rar') do_extract 'unrar' "unrar x -inul '$file'";;
+        *'.tar') do_extract 'tar' "tar xf '$file'";;
+        *'.tar.bz2') do_extract 'tar' "tar xjf '$file'";;
+        *'.tar.gz') do_extract 'tar' "tar xzf '$file'";;
+        *'.tar.xz') do_extract 'tar' "tar xJf '$file'";;
+        *) echo -e "[$YELLOW WARN $NC] Can not extract $file";;
+    esac
+done
