update

diff --git a/resource/utils/bin/extract b/resource/utils/bin/extract
--- a/resource/utils/bin/extract
+++ b/resource/utils/bin/extract
@@ -8,66 +8,50 @@ NC='\033[0m'
 
 USAGE="$GRAY===================USAGE
 $YELLOW$(basename "$0") $BLUE<archive(s)>$NC
-
-extracts the given archive(s)
 "
-if (( ! "$#" ));then
+if [[ "$#" -eq 0 ]];then
     echo -e "$USAGE"
     exit 1
 fi
-
 is_installed() {
-    local app="$1"
-    grep -q 'install ok installed'\
-        <<<"$(dpkg-query -W -f='${Status}' "$app" 2>'/dev/null')"\
+    local pkg="$1"
+    dpkg-query -W -f='${Status}' "$pkg"\
+        | grep -q "install ok installed"\
         && return 0
-
-    echo -e "$app needed, install ?"
-    select x in 'Yes' 'No';do
-        case "$x" in
-        'Yes')
-            echo -e "${BLUE}Installing$NC $app..."
-            if ! sudo apt install -y "$app" &> '/dev/null';then
-                echo -e "[$RED KO $NC] apt failed"
-                return 1
-            fi
-            echo -e "[$GREEN OK $NC]"
-            return 0
-            ;;
-        'No') return 1;;
-        esac
-    done
+    echo -e "$pkg needed, install ?"
+    read -p "y/n: " -n 1 -r
+    echo
+    [[ "$REPLY" != 'y' ]] && return 1
+    sudo apt install -y "$pkg" || return 1
+    return 0
 }
 do_extract() {
     local app="$1"
     local cmd="$2"
-    if ! is_installed "$app";then
-        echo -e "[$YELLOW WARN $NC] can not extract $file"
-        return 1
-    fi
-    echo -e "${BLUE}Extracting$NC $file..."
+    is_installed "$app" || return 1
+    echo -e "${BLUE}extracting$NC $FILE..."
     eval "$cmd"
-    echo -e "[$GREEN EXTRACTED $NC] $file"
+    echo -e "[$GREEN OK $NC] $FILE"
     return 0
 }
-while (( "$#" ));do
-    file="$1"
-    echo "file: $file"
+while [[ "$#" -gt 0 ]];do
+    FILE="$1"
     shift
-    if [[ ! -f "$file" ]];then
-        echo -e "[$YELLOW WARN $NC] $file not found"
+    if [[ ! -e "$FILE" ]];then
+        echo -e "[$YELLOW ERR $NC] not found: $FILE"
         continue
     fi
-    case "$file" in
-        *'.zip') do_extract 'unzip' "unzip -q $file";;
-        *'.rar') do_extract 'unrar' "unrar x -o- $file";;
-        *'.iso') do_extract 'p7zip-full' "7z x $file";;
-        *'.tar') do_extract 'tar' "tar xf $file";;
-        *'.tar.gz') do_extract 'tar' "tar xzf $file";;
-        *'.tar.xz') do_extract 'tar' "tar xJf $file";;
-        *'.tar.bz2') do_extract 'tar' "tar xjf $file";;
-        *'.gz') do_extract 'gzip' "gunzip $file";;
-        *'.tgz') do_extract 'tar' "tar xzf $file";;
-        *) echo -e "[$YELLOW WARN $NC] Can not extract $file";;
+    case "$FILE" in
+    # <package name> <extract command>
+    *'.zip') do_extract 'unzip' "unzip -q $FILE";;
+    *'.rar') do_extract 'unrar' "unrar x -o- $FILE";;
+    *'.iso') do_extract 'p7zip-full' "7z x $FILE";;
+    *'.tar') do_extract 'tar' "tar xf $FILE";;
+    *'.tar.gz') do_extract 'tar' "tar xzf $FILE";;
+    *'.tar.xz') do_extract 'tar' "tar xJf $FILE";;
+    *'.tar.bz2') do_extract 'tar' "tar xjf $FILE";;
+    *'.gz') do_extract 'gzip' "gunzip $FILE";;
+    *'.tgz') do_extract 'tar' "tar xzf $FILE";;
+    *) echo -e "[$YELLOW ERR $NC] unknown type: $FILE";;
     esac
 done
diff --git a/resource/utils/bin/gitpush b/resource/utils/bin/gitpush
--- a/resource/utils/bin/gitpush
+++ b/resource/utils/bin/gitpush
@@ -1,267 +1,204 @@
 #!/bin/bash
-# 0 20 * * * /home/skalya/.local/bin/gitpush /home/skalya/.local/share/git
-PATH='/bin:/sbin:/usr/bin:/usr/sbin'
+# crontab -e => 0 20 * * * ~/.local/bin/gitpush ~/.local/share/git
+RED="\033[0;31m"
+GREEN="\033[0;32m"
+YELLOW="\033[0;33m"
+BLUE="\033[0;34m"
+GRAY="\033[0;37m"
+NC="\033[0m"
 
-GREEN='\033[0;32m'
-YELLOW='\033[0;33m'
-RED='\033[0;31m'
-BLUE='\033[0;34m'
-GRAY='\033[0;37m'
-NC='\033[0m'
+USAGE="$GRAY===================USAGE$NC
+$YELLOW$(basename "$0") $BLUE<path> $GREEN[options]$NC
 
-USAGE="${GRAY}===================usage${NC}
-${YELLOW}$(basename "$0") ${BLUE}<path> ${GREEN}[options]${NC}
+Navigate from the specified path
+Push all changes to the remote repository
+Read .add files to add specific files instead of *
+Read .msg files to change default commit message
+Read .ord files to change push order
 
-Navigate from the specified path.
-Push all changes to the remote repository.
-Read .add files to add specific files instead of *.
-Read .msg files to change default commit message.
-Read .ord files to change push order.
-
-[options]:
-${GREEN}-e, --exclude DIR[S]${NC}
-* Don't push changes from specified directories.
-${GREEN}-a, --add STRING[S]${NC}
-* Change default files to add.
-${GREEN}-m, --message STRING${NC}
-* Change default commit message.
-${GREEN}--rm-add [DIR[S]]${NC}
-* Remove .add files from all/specified directories.
-${GREEN}--rm-msg [DIR[S]]${NC}
-* Remove .msg files from all/specified directories.
-${GREEN}-s, --silent${NC}
-* Run in silent mode."
-
-ft_echo() {
-    if [ -z "$SILENT" ]; then
-        echo -ne "$@"
-    fi
-}
-#
-#
-#==================================PARSE
-if [ "$#" -lt 1 ]; then
+$GREEN[options]$NC:
+-e, --exclude <dir(s)>
+    $RED*$NC Don't push changes from specified directories
+-a, -add <items(s)>
+    $RED*$NC Change default files/folders to add
+-m, --message <string>
+    $RED*$NC Change default commit message
+--rm-add [dir(s)]
+    $RED*$NC Remove .add files from all/specified directories
+--rm-msg [dir(s)]
+    $RED*$NC Remove .msg files from all/specified directories
+-s, --silent
+    $RED*$NC Run in silent mode
+"
+if [[ "$#" -lt 1 ]];then
     echo -e "$USAGE"
     exit 1
 fi
-
+ft_echo() {
+    [[ "$SILENT" ]] || echo -ne "$@"
+}
 ROOT="$1"
-EXCLUDE=()
 shift
+TO_ADD=("*")
+MESSAGE="update"
 
-TO_ADD=('*')
-MESSAGE='update'
-
-RM_ADD=()
-RM_MSG=()
-
-while [ "$#" -gt 0 ]; do
+err() {
+    ft_echo "[$RED ERR $NC] $1\n"
+    exit 1
+}
+while [[ "$#" -gt 0 ]];do
     case "$1" in
-        '-e'|'--exclude')
+    "-e" | "--exclude")
+        [[ "$#" -eq 1 ]] && err "Missing argument for $GREEN$1$NC"
+        shift
+        while [[ "$#" -gt 0 ]];do
+            [[ "${1:0:1}" == "-" ]] && break
+            EXCLUDE+=("$1")
             shift
-            while [ "$#" -gt 0 ]; do
-                if [ "${1:0:1}" = '-' ]; then
-                    break
-                fi
-                EXCLUDE=("${EXCLUDE[@]}" "$1")
-                shift
-            done
-            if [ "${#EXCLUDE[@]}" -eq 0 ]; then
-                ft_echo "[$RED ERROR $NC] Missing argument for ${GREEN}--exclude${NC}\n"
-                exit 1
-            fi
-            ;;
-        '-a'|'--add')
+        done
+        ;;
+    "-a" | "-add")
+        [[ "$#" -eq 1 ]] && err "Missing argument for $GREEN$1$NC"
+        shift
+        while [[ "$#" -gt 0 ]];do
+            [[ "${1:0:1}" == "-" ]] && break
+            TO_ADD+=("$1")
             shift
-            while [ "$#" -gt 0 ]; do
-                if [ "${1:0:1}" = '-' ]; then
-                    break
-                fi
-                TO_ADD=("${TO_ADD[@]}" "$1")
-                shift
-            done
-            if [ "${#TO_ADD[@]}" -eq 0 ]; then
-                ft_echo "[$RED ERROR $NC] Missing argument for ${GREEN}--add${NC}\n"
-                exit 1
-            fi
-            ;;
-        '-m'|'--message')
+        done
+        ;;
+    "-m" | "--message")
+        [[ "$#" -eq 1 ]] && err "Missing argument for $GREEN$1$NC"
+        shift
+        MESSAGE="$1"
+        ;;
+    "--rm-add")
+        shift
+        while [[ "$#" -gt 0 ]];do
+            [[ "${1:0:1}" == "-" ]] && break
+            RM_ADD+=("$1")
             shift
-            if [ "$#" -eq 0 ]; then
-                ft_echo "[$RED ERROR $NC] Missing argument for ${GREEN}--message${NC}\n"
-                exit 1
-            fi
-            MESSAGE="$1"
-            ;;
-        '--rm-add')
+        done
+        [[ "${#RM_ADD[@]}" -eq 0 ]] && RM_ADD=("*")
+        ;;
+    "--rm-msg")
+        shift
+        while [[ "$#" -gt 0 ]];do
+            [[ "${1:0:1}" == "-" ]] && break
+            RM_MSG+=("$1")
             shift
-            while [ "$#" -gt 0 ]; do
-                if [ "${1:0:1}" = '-' ]; then
-                    break
-                fi
-                RM_ADD=("${RM_ADD[@]}" "$1")
-                shift
-            done
-            if [ "${#RM_ADD[@]}" -eq 0 ]; then
-                RM_ADD=('*')
-            fi
-            ;;
-        '--rm-msg')
-            shift
-            while [ "$#" -gt 0 ]; do
-                if [ "${1:0:1}" = '-' ]; then
-                    break
-                fi
-                RM_MSG=("${RM_MSG[@]}" "$1")
-                shift
-            done
-            if [ "${#RM_MSG[@]}" -eq 0 ]; then
-                RM_MSG=('*')
-            fi
-            ;;
-        '-s'|'--silent')
-            shift
-            SILENT=1
-            ;;
-        *)
-            ft_echo "[$RED ERROR $NC] Unknown option: $1\n"
-            exit 1
-            ;;
+        done
+        [[ "${#RM_MSG[@]}" -eq 0 ]] && RM_MSG=("*")
+        ;;
+    "-s" | "--silent")
+        shift;
+        SILENT=1
+        ;;
+    *) err "Unknown option $GREEN$1$NC";;
     esac
 done
-#
-#
-#================================== RUN
-if ! cd "$ROOT"; then
-    ft_echo "[$RED ERROR $NC] Failed to 'cd $ROOT'\n"
-    exit 1
-fi
+cd "$ROOT" || exit 1
 
-if [ "${#EXCLUDE[@]}" -gt 0 ]; then
-    for target in "${EXCLUDE[@]}"; do
-        excluded=$(find . -type d -name "$target")
-        if [ -z "$excluded" ]; then
-            ft_echo "[$RED ERROR $NC] $target not found from $ROOT\n"
-            exit 1
-        else
-            repo=$(find "$excluded" -type d -name '.git')
-            if [ -z "$repo" ]; then
-                ft_echo "[$RED ERROR $NC] $target is not a git repository\n"
-                exit 1
-            fi
-        fi
-    done
-fi
+for target in "${EXCLUDE[@]}";do
+    excluded="$(find . -type d -name "$target")"
+    [[ "$excluded" ]] || err "$target not found"
+
+    repo="$(find "$excluded" -type d -name ".git")"
+    [[ "$repo" ]] || err "$target is not a git repository"
+done
 
 do_it() {
-    local cwd=$(pwd)
-    if find "$cwd" -mindepth 1 -maxdepth 1 -type f -name '.ord' | grep -q '.ord'; then
-        local order=$(cat '.ord')
-        local targets=($(find "$cwd" -mindepth 1 -maxdepth 1 -type d))
+    local cwd="$(pwd)"
+    local targets=($(find "$cwd" -mindepth 1 -maxdepth 1 -type d))
+
+    #==================== Sorting targets
+    if [[ "$(find "$cwd" -mindepth 1 -maxdepth 1\
+        -type f -name ".ord")" ]]
+    then
+        local order="$(cat ".ord")"
         local ordered=()
-        while [ "${#targets[@]}" -gt 0 ]; do
-            local next=$(echo "$order" | head -n 1)
-            for target in "${targets[@]}"; do
-                local name=$(basename "$target")
-                if [ "$name" = "$next" ]; then
-                    ordered=("${ordered[@]}" "$target")
-                    targets=($(printf "%s\n" "${targets[@]}" | grep -v "^$target$"))
-                    order=$(echo "$order" | tail -n +2)
+        while [[ "${#targets[@]}" -gt 0 ]];do
+            local next="$(head -n1 <<< "$order")"
+
+            for target in "${targets[@]}";do
+                local name="$(basename "$target")"
+                if [[ "$name" == "$next" ]];then
+
+                    ordered+=("$target")
+                    targets=($(printf "%s\n" "${targets[@]}"\
+                        | grep -v "^$target$"))
+                    order="$(tail -n+2 <<< "$order")"
                     break
                 fi
             done
         done
         targets=("${ordered[@]}")
     else
-        local targets=($(find "$cwd" -mindepth 1 -maxdepth 1 -type d | sort))
+        targets=($(sort <<< "${targets[@]}"))
     fi
-    if ! echo "${targets[@]}" | grep -q "$cwd/.git"; then
-        for target in "${targets[@]}"; do
-            local name=$(basename "$target")
-            if printf "%s\n" "${EXCLUDE[@]}" | grep -q "^$name$"; then
-                continue
-            elif ! cd "$target"; then
-                ft_echo "[$YELLOW WARN $NC] Failed to 'cd $target'\n"
-                continue
-            fi
+
+    if ! grep -q "$cwd/.git" <<< "${targets[@]}";then
+    #==================== Not a git repository, go deeper
+        for target in "${targets[@]}";do
+            local name="$(basename "$target")"
+            printf "%s\n" "${EXCLUDE[@]}" | grep -q "^$name$"\
+                && continue
+            cd "$target" || continue
             do_it
         done
-    else
-        local state=$(git status -s)
-        if [ -z "$state" ]; then
-            ft_echo "$cwd [$GREEN OK $NC]\n"
-            return
-        fi
-        if ! git pull &>'/dev/null'; then
-            ft_echo "$cwd [$RED KO $NC]\n"
-            ft_echo "Non-zero returned from 'git pull'\n"
-            return
-        fi
-        if echo "${targets[@]}" | grep -q "$cwd/.add"; then
-            TO_ADD=$(cat '.add')
-            if [ "${#RM_ADD[@]}" -gt 0 ]; then
-                rm_it "${RM_ADD[@]}" "$cwd/.add"
-            fi
-        fi
-        if echo "${targets[@]}" | grep -q "$cwd/.msg"; then
-            MESSAGE=$(cat '.msg')
-            if [ "${#RM_MSG[@]}" -gt 0 ]; then
-                rm_it "${RM_MSG[@]}" "$cwd/.msg"
-            fi
-        fi
-        for target in "${TO_ADD[@]}"; do
-            git add "$target" &>'/dev/null'
-            case "$?" in
-                0) ;;
-                1) ;;
-                128)
-                    ft_echo "[$YELLOW WARN $NC] $target not found in $cwd\n"
-                    return
-                    ;;
-                *)
-                    ft_echo "[$YELLOW WARN $NC] Non-zero returned from 'git add $target'\n"
-                    return
-                    ;;
-            esac
-        done
-        ft_echo "${BLUE}Pushing${NC} $cwd..."
-        if ! git commit -m "$MESSAGE" &>'/dev/null'; then
-            ft_echo "[$RED KO $NC]\n"
-            ft_echo "Non-zero returned from 'git commit -m \"$MESSAGE\"'\n"
-            return
-        fi
-        if ! git push &>'/dev/null'; then
-            ft_echo "[$RED KO $NC]\n"
-            ft_echo "Non-zero returned from 'git push'\n"
-            return
-        fi
-        ft_echo "[$GREEN OK $NC]\n"
-        state=$(git status -s)
-        if [ ! -z "$state" ]; then
-            ft_echo "[$YELLOW WARN $NC] Uncommitted changes in $cwd\n"
-        fi
+        return 0
     fi
-}
 
+    local state="$(git status -s)"
+    if [[ ! "$state" ]];then
+    #==================== Nothing to commit
+        ft_echo "$cwd [$GREEN OK $NC]\n"
+        return 0
+    fi
+
+    ft_echo "${BLUE}Pushing${NC} $cwd..."
+    git pull 1>"/dev/null" || return 1
+
+    #==================== .add & .msg files
+    if grep -q "$cwd/.add" <<< "${targets[@]}";then
+        TO_ADD="$(cat ".add")"
+        [[ "${#RM_ADD[@]}" -gt 0 ]]\
+            && rm_it "${RM_ADD[@]}" "$cwd/.add"
+    fi
+    if grep -q "$cwd/.msg" <<< "${targets[@]}";then
+        MESSAGE="$(cat ".msg")"
+        [[ "${#RM_MSG[@]}" -gt 0 ]]\
+            && rm_it "${RM_MSG[@]}" "$cwd/.msg"
+    fi
+
+    #==================== Add, commit & push
+    for target in "${TO_ADD[@]}";do git add "$target";done
+    git commit -m "$MESSAGE" 1>"/dev/null" || return 1
+    git push 1>"/dev/null" || return 1
+    ft_echo "[$GREEN OK $NC]\n"
+
+    [[ "$(git status -s)" ]]\
+        && ft_echo "[$YELLOW WARN $NC] $cwd: Uncommitted changes\n"
+}
 rm_it() {
     local targets=("${@:1:$#-1}")
     local file="${@: -1}"
-    if [ "${#targets[@]}" -eq 0 ]; then
-        return
+    local count="${#targets[@]}"
+    [[ "$count" -eq 0 ]] && return 0
+
+    if [[ "$count" -eq 1 && "${targets[0]}" == "*" ]];then
+        rm "$file" || return 1
+        return 0
     fi
-    if [ "${#targets[@]}" -eq 1 -a "${targets[0]}" = '*' ]; then
-        rm "$file" &>'/dev/null'
-    else
-        local dir=$(basename $(dirname "$file"))
-        for target in "${targets[@]}"; do
-            if [ "$target" = "$dir" ]; then
-                rm "$file" &>'/dev/null'
-                return
-            fi
-        done
-    fi
+    local dir="$(basename "$(dirname "$file")")"
+    for target in "${targets[@]}";do
+        if [[ "$target" == "$dir" ]];then
+            rm "$file" || return 1
+            return 0
+        fi
+    done
+    return 1
 }
 
-ft_echo "$GRAY===================from $ROOT$NC\n"
+ft_echo "$GRAY===================FROM: $ROOT$NC\n"
 do_it
-ft_echo "$GRAY===================done$NC\n"
+ft_echo "$GRAY===================DONE$NC\n"
